"""wechat to unionid

Revision ID: 06153d1326c4
Revises: 43579ffa696a
Create Date: 2023-10-13 18:17:15.532705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '06153d1326c4'
down_revision: Union[str, None] = '43579ffa696a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('unionid', sa.VARCHAR(length=64), nullable=False))
    op.drop_column('user', 'wechat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wechat_id', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('user', 'unionid')
    # ### end Alembic commands ###
