"""feat: add comment when add pain data

Revision ID: 2c10aae8d6d6
Revises: f483d0217b9b
Create Date: 2024-02-01 16:09:06.558401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c10aae8d6d6'
down_revision: Union[str, None] = 'f483d0217b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pain_data', sa.Column('comment', sa.VARCHAR(length=1024), nullable=True))
    op.alter_column('pain_data', 'pain_level_custom',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pain_data', 'pain_level_custom',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.drop_column('pain_data', 'comment')
    # ### end Alembic commands ###
