"""pationid for varchar36 in pain_data

Revision ID: 30fff3b4e5f4
Revises: 8dc7c714f9f2
Create Date: 2023-10-19 15:37:25.434522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30fff3b4e5f4'
down_revision: Union[str, None] = '8dc7c714f9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'receiver',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('feedback', 'sender',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('pain_data', 'patient_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pain_data', 'patient_id',
               existing_type=sa.VARCHAR(length=36),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('feedback', 'sender',
               existing_type=sa.VARCHAR(length=36),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('feedback', 'receiver',
               existing_type=sa.VARCHAR(length=36),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    # ### end Alembic commands ###
