"""feat: use uuid as id.

Revision ID: 43579ffa696a
Revises: 874015daf6f9
Create Date: 2023-10-07 15:11:33.031627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43579ffa696a'
down_revision: Union[str, None] = '874015daf6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('hospital', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('pain_data', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('pain_data', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('hospital', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('feedback', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    # ### end Alembic commands ###
