"""feat: update pain_data

Revision ID: 6330494ca7e8
Revises: cc99352bdb1f
Create Date: 2024-02-02 22:38:40.054328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6330494ca7e8'
down_revision: Union[str, None] = 'cc99352bdb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pain_data',
    sa.Column('patient_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('pain_level_custom', sa.Float(), nullable=False),
    sa.Column('pain_level', sa.VARCHAR(length=32), nullable=True),
    sa.Column('pain_data_path', sa.VARCHAR(length=128), nullable=False),
    sa.Column('record_path', sa.VARCHAR(length=128), nullable=True),
    sa.Column('comment', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pain_data')
    # ### end Alembic commands ###
