"""init feedback model.

Revision ID: 7037389f77a2
Revises: d2169477e8b0
Create Date: 2023-09-16 14:12:53.553626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7037389f77a2'
down_revision: Union[str, None] = 'd2169477e8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column('hospital', sa.Column('updated_time', sa.DateTime(), nullable=True))
    op.drop_column('hospital', 'updated_at')
    op.drop_column('hospital', 'created_at')
    op.add_column('user', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_time', sa.DateTime(), nullable=True))
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'updated_time')
    op.drop_column('user', 'created_time')
    op.add_column('hospital', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('hospital', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.drop_column('hospital', 'updated_time')
    op.drop_column('hospital', 'created_time')
    # ### end Alembic commands ###
