"""hospital_id to varchar

Revision ID: 8dc7c714f9f2
Revises: 06153d1326c4
Create Date: 2023-10-16 15:34:30.741739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8dc7c714f9f2'
down_revision: Union[str, None] = '06153d1326c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hospital_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('user', 'doctor_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'doctor_id',
               existing_type=sa.VARCHAR(length=36),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('user', 'hospital_id',
               existing_type=sa.VARCHAR(length=36),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    # ### end Alembic commands ###
