"""update pain_level as a string

Revision ID: 9f509f31536c
Revises: 30fff3b4e5f4
Create Date: 2023-10-20 20:31:37.110945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f509f31536c'
down_revision: Union[str, None] = '30fff3b4e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pain_data', 'pain_level',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pain_data', 'pain_level',
               existing_type=sa.VARCHAR(length=32),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
