"""feat: add user pswd

Revision ID: f483d0217b9b
Revises: 9f509f31536c
Create Date: 2024-01-15 16:56:50.097270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f483d0217b9b'
down_revision: Union[str, None] = '9f509f31536c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('service_unionid', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_column('user', 'service_unionid')
    # ### end Alembic commands ###
